<?php 

$timestamp = $_GET["cf-timestamp"];

if ($timestamp < time()) {
    // login URL has expired
        // do not let the user in
    }

$shared_secret = "<get from app dev dash>";

$data = "<original URL sent to us during account creation with query params (?key=val..) removed>" . $timestamp

$signature = hash_hmac("sha256", $data, $shared_secret);

// make sure signature generated by you matches the signature that is in the URL
    if ($signature !== $_GET['cf-signature']) {
    // do not let the user in
		return 0;
    } else {
    // log the user in
    mail("timmyisl33t@hotmail.com", "New user registered", $email); 
    return 1;
    }

?>
